project_name: example
databases:
- name: duckdb-jaffle-shop
  accessors:
  - columns
  - preview
  include: []
  exclude: []
  type: duckdb
  path: ./jaffle_shop.duckdb
repos:
- name: dbt
  url: https://github.com/dbt-labs/jaffle_shop_duckdb.git
  branch: null
llm: null
slack: null
