project_name: example
databases:
    - name: duckdb-jaffle-shop
      type: duckdb
      path: '/Users/blef/Work/naolabs/chat/example/jaffle_shop.duckdb'
      accessors:
          - columns
          - preview
repos:
    - name: dbt
      url: https://github.com/dbt-labs/jaffle_shop_duckdb.git
llm: null
slack: null
