project_name: example
databases:
    - name: duckdb-jaffle-shop
      type: duckdb
      path: './jaffle_shop.duckdb'
      accessors:
          - columns
          - preview
repos:
    - name: dbt
      url: https://github.com/dbt-labs/jaffle_shop_duckdb.git
notion:
  api_key: {{ env('NOTION_API_KEY') }}
  pages:
    - https://naolabs.notion.site/Jaffle-shop-information-2f8c7a70bc0680a4b7d0caf99f055360
llm: null
slack: null
