name: Deploy to GCP instance

on:
    workflow_run:
        workflows: ['Docker Build & Push']
        types:
            - completed
        branches:
            - main
            - '**docker'

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        environment:
            name: ${{ github.event.workflow_run.head_branch }}
        name: Deploy to GCP instance
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Deploy with remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VM_HOST }}
                  username: github-action
                  key: ${{ secrets.PRIVATE_KEY }}
                  script: |
                      docker pull getnao/nao:${{ github.event.workflow_run.head_sha }}
                      docker rm -f nao-chat 2>/dev/null || true
                      docker run -p 5005:5005 \
                        -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                        -e BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }} \
                        -e NAO_DEFAULT_PROJECT_PATH=/app/example \
                        --name nao-chat \
                        -d getnao/nao:${{ github.event.workflow_run.head_sha }}
